use_frameworks!

target 'SVKit_Example' do
  pod 'SVKit', :path => '../'

  target 'SVKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
